version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BiteHub
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data: