"""Remove calories and add icon_url for ingredients

Revision ID: 42c9da378c9d
Revises: c640ee4bbe3a
Create Date: 2025-09-06 17:13:55.289998

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '42c9da378c9d'
down_revision = 'c640ee4bbe3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sqlalchemy_utils.types.url.URLType(), nullable=False))
        batch_op.drop_column('calories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('icon_url')

    # ### end Alembic commands ###
