"""fixed table rating, rename and add ID

Revision ID: 4d97c2651923
Revises: aa6ce64e0503
Create Date: 2025-09-11 21:31:00.477969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d97c2651923'
down_revision = 'aa6ce64e0503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(comment)) > 0', name='ck_ratings_comment_required'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_ratings_rating_valid'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', name='uq_reviews_user_id_recipe_id')
    )
    op.drop_table('ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipe_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('length(TRIM(BOTH FROM comment)) > 0', name=op.f('ck_ratings_comment_required')),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_ratings_rating_valid')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('ratings_recipe_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ratings_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id', name=op.f('ratings_pkey'))
    )
    op.drop_table('reviews')
    # ### end Alembic commands ###
