"""Add column created_at in recipes

Revision ID: 825953c14cb4
Revises: 42c9da378c9d
Create Date: 2025-09-06 17:40:50.494058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825953c14cb4'
down_revision = '42c9da378c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
