"""remove cloumn quantity in recipe_ingredients

Revision ID: a886ed20fee0
Revises: 4d97c2651923
Create Date: 2025-09-12 20:35:52.171886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a886ed20fee0'
down_revision = '4d97c2651923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.VARCHAR(length=40), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
