"""Create tables Recipes, RecipeIngredients, Ratings and RecipeCategories

Revision ID: b0714460f6c6
Revises: c6602580af03
Create Date: 2025-09-05 18:16:59.182528

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b0714460f6c6'
down_revision = 'c6602580af03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('duration > 0', name='ck_recipes_duration_valid'),
    sa.CheckConstraint('length(trim(description)) > 0', name='ck_recipes_description_required'),
    sa.CheckConstraint('length(trim(title)) > 0', name='ck_recipes_title_required'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'title', name='uq_recipes_author_id_title')
    )
    op.create_table('ratings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(comment)) > 0', name='ck_ratings_comment_required'),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_ratings_rating_valid'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_table('recipe_categories',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'category_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_recipe_ingredients_quantity_valid'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe_categories')
    op.drop_table('ratings')
    op.drop_table('recipes')
    # ### end Alembic commands ###
