"""create table recipe-steps

Revision ID: e153a8f28f5f
Revises: b0714460f6c6
Create Date: 2025-09-06 11:48:32.587812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e153a8f28f5f'
down_revision = 'b0714460f6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.CheckConstraint('length(trim(description)) > 0', name='ck_recipe_steps_description_required'),
    sa.CheckConstraint('step_number >= 1', name='ck_recipe_steps_step_number_valid'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_steps')
    # ### end Alembic commands ###
