"""add cascade delete on recipes

Revision ID: f1dcea62a1be
Revises: a886ed20fee0
Create Date: 2025-09-15 19:13:39.243703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dcea62a1be'
down_revision = 'a886ed20fee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipe_categories_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipe_ingredients_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipe_ingredients_recipe_id_fkey'), 'recipes', ['recipe_id'], ['id'])

    with op.batch_alter_table('recipe_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipe_categories_recipe_id_fkey'), 'recipes', ['recipe_id'], ['id'])

    # ### end Alembic commands ###
